source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Jekyll version
gem "jekyll", "~> 4.3.2"

# Theme
gem "just-the-docs", "~> 0.8.2"

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-seo-tag", "~> 2.8"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# GitHub Pages
gem "github-pages", group: :jekyll_plugins
